In [1]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
sc=StandardScaler()

In [3]:
data=pd.read_csv('spam.csv')
data.columns

Index(['Category', 'Message'], dtype='object')

In [26]:
x=data.iloc[:,1].values
y=data.iloc[:,0].values

In [27]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x=le.fit_transform(x)
print(x)

[1080 3126  999 ... 3313 3932 3437]


In [28]:
import numpy as np
x=np.array(x).reshape(-1,1)
x

array([[1080],
       [3126],
       [ 999],
       ...,
       [3313],
       [3932],
       [3437]])

In [13]:
le=LabelEncoder()
y=le.fit_transform(y)
print(y)

[0 0 1 ... 0 0 0]


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [32]:
x_train,x_test,y_train,y_test,=train_test_split(x,y,test_size=4, random_state=6)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[2945]
 [3946]
 [  10]
 ...
 [3450]
 [4593]
 [1810]]
[[2051]
 [2491]
 [4054]
 [1026]]
['ham' 'ham' 'ham' ... 'ham' 'spam' 'ham']
['ham' 'ham' 'ham' 'spam']


In [33]:
classifier=RandomForestClassifier(criterion='gini')
classifier.fit(x , y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [34]:
y_pred=classifier.predict([[3]])
print (y_pred)

['ham']
